config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'home#index'
  namespace :admin do
      resources :substreams
      resources :card_settings
      resources :students do
        collection do
          post :import
        end
      end
      resources :streams 
      resources :schools
      resources :cards, only: [:index]
      root to: "cards#index"
    end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/student.rb
class Student < ApplicationRecord
  belongs_to :school
  belongs_to :stream
  belongs_to :substream
  has_one_attached :photo
  validates_associated :stream, :substream
  validates_presence_of :surname, :other_names, :gender

 

  def name
    "#{surname} #{other_names}"
  end

 def level
    "#{stream.name}  #{substream.name}"
  end


  enum gender:{Male:'Male', Female:'Female'} 
  
end

app/controllers/admin/students_controller.rb
module Admin
  class StudentsController < Admin::ApplicationController
    
    # Overwrite any of the RESTful controller actions to implement custom behavior
    # For example, you may want to send an email after a foo is updated.
    #
    # def update
    #   super
    #   send_foo_updated_email(requested_resource)
    # end
    def import
      file = params[:file]
      return redirect_to admin_students_path, notice: 'Only CSV please' unless file.content_type == 'text/csv'
  
      CsvImportStudentsService.new.call(file)
  
      redirect_to admin_students_path, notice: 'Users imported!'
    end

    # Override this method to specify custom lookup behavior.
    # This will be used to set the resource for the `show`, `edit`, and `update`
    # actions.
    #
    # def find_resource(param)
    #   Foo.find_by!(slug: param)
    # end

    # The result of this lookup will be available as `requested_resource`

    # Override this if you have certain roles that require a subset
    # this will be used to set the records shown on the `index` action.
    #
    # def scoped_resource
    #   if current_user.super_admin?
    #     resource_class
    #   else
    #     resource_class.with_less_stuff
    #   end
    # end

    # Override `resource_params` if you want to transform the submitted
    # data before it's persisted. For example, the following would turn all
    # empty values into nil values. It uses other APIs such as `resource_class`
    # and `dashboard`:
    #
    # def resource_params
    #   params.require(resource_class.model_name.param_key).
    #     permit(dashboard.permitted_attributes).
    #     transform_values { |value| value == "" ? nil : value }
    # end

    # See https://administrate-prototype.herokuapp.com/customizing_controller_actions
    # for more information


    
  end
end

app/helpers/student_helper.rb
module StudentHelper
   

end

app/views/admin/students/_form.html.erb
<%#
# Form Partial

This partial is rendered on a resource's `new` and `edit` pages,
and renders all form fields for a resource's editable attributes.

## Local variables:

- `page`:
  An instance of [Administrate::Page::Form][1].
  Contains helper methods to display a form,
  and knows which attributes should be displayed in the resource's form.

[1]: http://www.rubydoc.info/gems/administrate/Administrate/Page/Form
%>
<%= form_for([namespace, page.resource], html: { class: "form" }) do |f| %>
  <% if page.resource.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= t(
          "administrate.form.errors",
          pluralized_errors: pluralize(page.resource.errors.count, t("administrate.form.error")),
          resource_name: display_resource_name(page.resource_name, singular: true)
        ) %>
      </h2>
      <ul>
        <% page.resource.errors.full_messages.each do |message| %>
          <li class="flash-error"><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <% page.attributes(controller.action_name).each do |attribute| -%>
    <div class="field-unit field-unit--<%= attribute.html_class %> field-unit--<%= requireness(attribute) %>">
      <%= render_field attribute, f: f %>
    </div>
  <% end -%>
  <div class="form-actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/admin/students/_import.html.erb
<%= form_with url: import_admin_students_path, method: :post, class:"addons" do |form| %>
  <%= form.file_field :file, accept: ".csv" %>
  <%= form.button "Import" %>
<% end %>

app/views/admin/students/index.html.erb
<%#
# Index

This view is the template for the index page.
It is responsible for rendering the search bar, header and pagination.
It renders the `_table` partial to display details about the resources.

## Local variables:

- `page`:
  An instance of [Administrate::Page::Collection][1].
  Contains helper methods to help display a table,
  and knows which attributes should be displayed in the resource's table.
- `resources`:
  An instance of `ActiveRecord::Relation` containing the resources
  that match the user's search criteria.
  By default, these resources are passed to the table partial to be displayed.
- `search_term`:
  A string containing the term the user has searched for, if any.
- `show_search_bar`:
  A boolean that determines if the search bar should be shown.

[1]: http://www.rubydoc.info/gems/administrate/Administrate/Page/Collection
%>
<div style ="color:teal ">Add School then Streams then Substreams then Students </div>
<%= render "import"%>
<%=
  render("index_header",
    resources: resources,
    search_term: search_term,
    page: page,
    show_search_bar: show_search_bar,
  )

%>
<section class="main-content__body main-content__body--flush">
  <%= render(
    "collection",
    collection_presenter: page,
    collection_field_name: resource_name,
    page: page,
    resources: resources,
    table_title: "page-title"
  ) %>
  <%= render("pagination", resources: resources) %>
</section>