config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'home#index'
  namespace :admin do
      resources :substreams
      resources :card_settings
      resources :students do
        collection do
          post :import
        end
      end
      resources :streams 
      resources :schools
      resources :cards, only: [:index]
      root to: "cards#index"
    end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/controllers/admin/cards_controller.rb
module Admin
class CardsController < Admin::ApplicationController
 
  def index
    @students =Student.where(stream_id:params[:stream])
    # @students = students.includes(:stream , :substream, :school)
    @streams= Stream.all
    
  end





end
end

app/controllers/card_controller.rb
class CardController < ApplicationController
  def index
    @students =Student.all
    @school=SchoolDetail.find_by_id(1)
  end
end

app/helpers/card_helper.rb
module CardHelper
end

app/views/admin/cards/_form.html.erb
<%= form_with url: admin_root_path ,method: :get, class: "addons hide" do |form| %>
  <%= form.label :stream %>
  <%= select_tag :stream, options_from_collection_for_select(@streams, "id", "name"), prompt: "- Please select -" %>
  <div >
    <%= form.submit  "Generate card" %>
  </div>
<% end %>

app/views/admin/cards/index.html.erb
<%= render "form"%>
<div class= "cardprint">
  <% @students.each do |s| %>
    <div id="card" class="card ">
      <div class="school-details">
        <div class="logodiv">
          <%= image_tag(s.school.logo_resize ,alt: "logo") %>
        </div>
        <div> <%= s.school.name%>  <br>
          <%= s.school.address%></div>
      </div>
      <div class="">
        <div class="" >
          <div class="title">
            <h1>Student Identification Card</h1>
          </div>
          <div id="" class="card-middle">
            <div class="imgdiv">
              <%if s.photo.present?%>
                <%=  image_tag( s.photo ,alt: "image" ,class:"card-img") %>
              <% else %>
                <%=  image_tag( "default.jpg" ,class:"card-img") %>
              <% end %>
            </div>
            <div id= "" class= "student-data">
              <h1>Name:<%= s.name%></h1>
              <h1>Adm:<%= s.adm_no%></h1>
              <h1>UPI:<%= s.upi%></h1>
              <h1>Index:<%= s.index_no%></h1>
              <h1>Kcpe Yr:<%= s.kcpe_yr%></h1>
              <h1>Dob:<%= s.dob%></h1>
              <h1>Gender:<%= s.gender%></h1>
              <h1>Class:<%= s.level%> </h1>
            </div>
          </div>
        </div>
      </div>
    </div>
  <%end%>
</div>
<br>
<br>
<br>
<button  class= "addons hide" onclick=window.print()>Print</button>